[config]
# Set this to `false` to run the tasks at workspace root directory and not on the members
default_to_workspace = false
# Set this to `true` to avoid clashes with core commands (e.g. `cargo make publish` vs `cargo publish`)
skip_core_tasks = true

[tasks.fmt]
args    = ["fmt", "--all", "--check"]
command = "cargo"

[tasks.test]
args    = ["test", "--locked"]
command = "cargo"

[tasks.lint]
args    = ["clippy", "--tests", "--", "-D", "warnings"]
command = "cargo"

[tasks.build]
args    = ["build", "--release", "--locked", "--target", "wasm32-unknown-unknown"]
command = "cargo"

[tasks.optimize]
# https://hub.docker.com/r/cosmwasm/workspace-optimizer/tags https://hub.docker.com/r/cosmwasm/workspace-optimizer-arm64/tags
script = """
if [[ $(arch) == "arm64" ]]; then
  image="cosmwasm/workspace-optimizer-arm64"
else
  image="cosmwasm/workspace-optimizer"
fi

docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  ${image}:0.17.0
"""

[tasks.schema]
script = """
for d in packages/*; do
  if [ -d "$d" ]; then
    cd $d
    cargo schema
    cd ../..
  fi
done

for d in contracts/*; do
  if [ -d "$d" ]; then
    cd $d
    cargo schema
    cd ../..
  fi
done

rm -rf contracts/**/schema/raw
"""

[tasks.publish]
script = """
crates=(
  cw721
  cw721-base
  cw721-fixed-price
  cw721-metadata-onchain
  cw721-non-transferable
)

for crate in $crates; do
  cargo publish -p $crate
  echo "Sleeping before publishing the next crate..."
  sleep 30
done
"""

[tasks.format-toml]
script = """
taplo fmt
"""
